import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { t } from "../../shared/i18n";

// The notices for the open-source software this app ships, read from the
// app bundle itself, and the terms that govern cloud use.
export function LegalSettings() {
  const [open, setOpen] = useState(false);
  const [notices, setNotices] = useState<string>();
  // Set when the notices cannot be read; the section then leaves.
  const [missing, setMissing] = useState(false);
  function toggle() {
    const next = !open;
    setOpen(next);
    if (!next || notices !== undefined) return;
    void fetch("notices.txt")
      // The app serves its files without an HTTP status (0), so the text,
      // not the status, says whether the notices were found.
      .then((response) =>
        response.ok || response.status === 0 ? response.text() : "",
      )
      .then((text) => {
        if (!text.trim()) throw new Error();
        setNotices(text);
      })
      .catch(() => {
        setOpen(false);
        setMissing(true);
      });
  }
  return (
    <>
      <p className="settings-intro">
        {t(
          "Replies are generated by AI and may be inaccurate or inappropriate.",
        )}
      </p>
      <p className="settings-lead">
        {t(
          "Chats go straight to the Ark account you connect and follow its agreement; the Open Muse service only keeps your account, your encrypted Ark key and the background work you allow. The software it ships includes open-source components under their own licenses.",
        )}
      </p>
      {!missing && (
        <div className="settings-group">
          <button
            className="settings-disclosure"
            aria-expanded={open}
            onClick={toggle}
          >
            <strong>{t("Open source notices")}</strong>
            <ChevronDown size={17} className={open ? "open" : ""} />
          </button>
        </div>
      )}
      {open && (
        <div className="settings-group settings-notices">
          {notices === undefined ? (
            <p>{t("Loading…")}</p>
          ) : (
            <pre>{notices}</pre>
          )}
        </div>
      )}
    </>
  );
}
