-- Postgres schema for Volcengine deployments, equivalent to the D1 schema
-- after migrations 0001-0010. Integers are BIGINT (millisecond timestamps).
CREATE TABLE account_credentials (
  owner_id TEXT PRIMARY KEY,
  revision BIGINT NOT NULL CHECK (revision > 0),
  encrypted TEXT,
  updated_at BIGINT NOT NULL,
  mutation_id TEXT NOT NULL,
  issuer TEXT,
  last_seen_at BIGINT
);
CREATE TABLE account_devices (
  owner_id TEXT NOT NULL,
  device_id TEXT NOT NULL,
  platform TEXT NOT NULL CHECK (platform IN ('mac', 'ios')),
  app_version TEXT NOT NULL,
  revision BIGINT NOT NULL CHECK (revision > 0),
  encrypted TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  last_seen_at BIGINT NOT NULL,
  PRIMARY KEY (owner_id, device_id)
);
CREATE TABLE account_key_checks (
  owner_id TEXT PRIMARY KEY,
  window_start BIGINT NOT NULL,
  count BIGINT NOT NULL
);
CREATE TABLE account_rate_limits (
  owner_id TEXT NOT NULL,
  bucket TEXT NOT NULL,
  window_start BIGINT NOT NULL,
  count BIGINT NOT NULL,
  PRIMARY KEY (owner_id, bucket)
);
CREATE TABLE account_resources (
  kind TEXT NOT NULL,
  resource_id TEXT NOT NULL,
  owner_id TEXT NOT NULL,
  claimed_at BIGINT NOT NULL,
  PRIMARY KEY (kind, resource_id)
);
CREATE TABLE account_workspaces (
  owner_id TEXT NOT NULL,
  workspace_key TEXT NOT NULL,
  revision BIGINT NOT NULL CHECK (revision > 0),
  encrypted TEXT,
  pending TEXT,
  updated_at BIGINT NOT NULL,
  mutation_id TEXT NOT NULL,
  PRIMARY KEY (owner_id, workspace_key)
);
CREATE TABLE ark_connections (
  owner_id TEXT PRIMARY KEY,
  revision BIGINT NOT NULL CHECK (revision > 0),
  encrypted TEXT,
  updated_at BIGINT NOT NULL,
  mutation_id TEXT NOT NULL
);
CREATE TABLE runs (
  id TEXT PRIMARY KEY,
  owner_id TEXT NOT NULL,
  request_key TEXT NOT NULL,
  scheduled_for BIGINT NOT NULL,
  phase TEXT NOT NULL CHECK (phase IN (
    'queued', 'creating', 'ready', 'sending', 'running',
    'complete', 'failed', 'needs_attention'
  )),
  marker TEXT NOT NULL UNIQUE,
  event_id TEXT NOT NULL UNIQUE,
  session_id TEXT,
  prompt TEXT,
  error TEXT,
  lease_token TEXT,
  lease_until BIGINT,
  next_check_at BIGINT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  connection_hash TEXT,
  resume_phase TEXT,
  deadline_at BIGINT NOT NULL DEFAULT 0,
  UNIQUE (owner_id, request_key)
);
CREATE TABLE feed_items (
  sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id TEXT NOT NULL UNIQUE,
  owner_id TEXT NOT NULL,
  run_id TEXT NOT NULL REFERENCES runs(id),
  session_id TEXT NOT NULL,
  event_id TEXT NOT NULL,
  position BIGINT NOT NULL,
  content TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  UNIQUE (owner_id, session_id, event_id, position)
);
CREATE TABLE scheduler_triggers (
  nonce TEXT PRIMARY KEY,
  received_at BIGINT NOT NULL
);
CREATE TABLE schedules (
  owner_id TEXT PRIMARY KEY,
  enabled BIGINT NOT NULL DEFAULT 0 CHECK (enabled IN (0, 1)),
  timezone TEXT NOT NULL DEFAULT 'UTC',
  local_time TEXT NOT NULL DEFAULT '09:00',
  next_run_at BIGINT,
  revision BIGINT NOT NULL DEFAULT 0,
  updated_at BIGINT NOT NULL,
  consent_at BIGINT
);
CREATE TABLE upcoming_deliveries (
  owner_id TEXT NOT NULL,
  item_id TEXT NOT NULL,
  occurrence_at BIGINT NOT NULL,
  event_id TEXT NOT NULL,
  PRIMARY KEY (owner_id, item_id, occurrence_at)
);
CREATE TABLE upcoming_messages (
  event_id TEXT PRIMARY KEY,
  owner_id TEXT NOT NULL,
  session_id TEXT NOT NULL,
  phase TEXT NOT NULL CHECK (phase IN ('sending', 'sent', 'unconfirmed', 'rejected')),
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);
CREATE TABLE upcoming_targets (
  owner_id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL,
  language TEXT NOT NULL,
  enabled BIGINT NOT NULL CHECK (enabled IN (0, 1)),
  since BIGINT NOT NULL,
  revision BIGINT NOT NULL CHECK (revision > 0),
  state TEXT NOT NULL CHECK (state IN ('active', 'session_unavailable')),
  next_check_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);
CREATE INDEX feed_owner ON feed_items(owner_id, sequence);
CREATE INDEX runs_due ON runs(next_check_at, phase);
CREATE UNIQUE INDEX runs_one_active ON runs(owner_id) WHERE phase NOT IN ('complete', 'failed');
CREATE INDEX runs_owner ON runs(owner_id, created_at);
CREATE INDEX scheduler_triggers_received ON scheduler_triggers(received_at);
CREATE INDEX upcoming_deliveries_event ON upcoming_deliveries(event_id);
CREATE INDEX upcoming_messages_owner ON upcoming_messages(owner_id, created_at);
CREATE INDEX upcoming_targets_due ON upcoming_targets(enabled, state, next_check_at);
