// A check-in is an application initiation in the main conversation, sent only
// while the app is open. MA has no unsolicited-turn API, so the prompt remains
// an ordinary user event in its history and the client hides it by exact ID.
import {
  eventText,
  pendingCustomTools,
  pendingPermissions,
  type AgentEvent,
} from "./types";

export const checkInPolicy = {
  // The conversation must have been quiet this long before the companion
  // reaches out, and two check-ins are never closer than minGap.
  quietFor: 18 * 60 * 60 * 1000,
  minGap: 20 * 60 * 60 * 1000,
  // Local hours [from, until) in which a check-in may start.
  from: 8,
  until: 22,
  // Persisted initiations used to hide old prompts on this device.
  retained: 60,
};

export type CheckInRecord = {
  phase: "sending" | "unconfirmed" | "confirmed" | "rejected";
  session: string;
  eventId: string;
  text: string;
  at: number;
  replyId?: string;
};

const sameLocalDay = (a: number, b: number) =>
  new Date(a).toDateString() === new Date(b).toDateString();

export function checkInDue(input: {
  enabled: boolean;
  now: number;
  status: string;
  history: AgentEvent[];
  records: CheckInRecord[];
}) {
  const { now, history, records } = input;
  if (!input.enabled || input.status !== "idle") return false;
  const hour = new Date(now).getHours();
  if (hour < checkInPolicy.from || hour >= checkInPolicy.until) return false;
  // An unresolved initiation must be reconciled before another is considered.
  if (records.some((record) => record.phase === "sending")) return false;
  const latest = records.at(-1);
  if (
    latest &&
    latest.phase !== "rejected" &&
    (now - latest.at < checkInPolicy.minGap || sameLocalDay(latest.at, now))
  )
    return false;
  // A session waiting on an approval or a tool result is waiting on the person.
  if (pendingPermissions(history).length || pendingCustomTools(history).length)
    return false;
  const hidden = new Set(records.map((record) => record.eventId));
  // Welcome, check-in, and reminder prompts on any device are the app's, not
  // the person's.
  const fromApp = (event: AgentEvent) =>
    hidden.has(event.id) || /^<open-muse-[a-z]+>/.test(eventText(event));
  const messages = history.filter(
    (event) =>
      ["user.message", "agent.message"].includes(event.type) &&
      eventText(event).trim(),
  );
  // Only an established conversation is checked in on; first-run setup is
  // the welcome flow's job.
  if (
    !messages.some((event) => event.type === "user.message" && !fromApp(event))
  )
    return false;
  const last = messages.at(-1);
  if (!last || last.type !== "agent.message") return false;
  // Never stack a new question on an exchange the app started and the person
  // has not answered: a welcome, a check-in, or a reminder.
  const prompt = [...messages]
    .reverse()
    .find((event) => event.type === "user.message");
  if (prompt && fromApp(prompt)) return false;
  const at = Date.parse(last.processed_at ?? last.created_at ?? "");
  return Number.isFinite(at) && now - at >= checkInPolicy.quietFor;
}

const checkInOpening =
  "<open-muse-checkin>\nThe app is opening a check-in in this person's main conversation";
// The app's own check-in prompt, recognized on any device that shows it.
export const isCheckInPrompt = (text: string) =>
  text.startsWith(checkInOpening) && text.endsWith("</open-muse-checkin>");

export function checkInPrompt(language: string, now: Date) {
  const locale = /^[a-z]{2,3}(?:-[a-z0-9]{2,8}){0,3}$/i.test(language)
    ? language
    : "en";
  const local = now.toLocaleString("en-US", {
    weekday: "long",
    hour: "numeric",
    minute: "2-digit",
  });
  return `${checkInOpening} after a quiet period. This message was generated by the app, not written by the person. Their local time is ${local}. Reply in the language of locale ${locale}, unless personal memory specifies a different language.

Quietly read the latest personal memory, persona, and goals, and consider the recent conversation. Reach out first as their companion with one short, specific question about something real: progress on an active goal, a plan or topic they mentioned recently, or a stated preference. If nothing specific applies, ask a light, genuine question that fits their local time. Use at most two short sentences and 40 words, in the companion's own voice and persona. When a few likely answers exist, add one muse-choice block with 2 to 4 short options and put the question only in the block; otherwise ask in prose. Do not invent facts, recap old answers, list capabilities, or claim reminders, notifications, or background work. Do not change memory or goals unless they answer with something worth saving. Do not mention this initiation or internal files. Stop after the question and wait for their answer.
</open-muse-checkin>`;
}
