// Emoji offered as reactions, by category, each with a short English name
// for search. Names are UI copy: they are translated through the catalog.
export type EmojiCategory = {
  label: string;
  icon: string;
  emoji: readonly (readonly [emoji: string, name: string])[];
};

// The quick reactions offered above a pressed message.
export const quickReactions = ["👍", "❤️", "😂", "😮", "😢", "🙏", "🔥", "🎉"];

export const emojiCategories: readonly EmojiCategory[] = [
  {
    label: "Smileys & Emotion",
    icon: "😀",
    emoji: [
      ["😀", "grinning face"],
      ["😃", "grinning face with big eyes"],
      ["😄", "grinning face with smiling eyes"],
      ["😁", "beaming face"],
      ["😆", "laughing face"],
      ["😅", "sweat smile"],
      ["😂", "tears of joy"],
      ["🤣", "rolling on the floor laughing"],
      ["😊", "smiling face"],
      ["😇", "halo"],
      ["🙂", "slight smile"],
      ["🙃", "upside-down face"],
      ["😉", "winking face"],
      ["😌", "relieved face"],
      ["😍", "heart eyes"],
      ["🥰", "smiling face with hearts"],
      ["😘", "blowing a kiss"],
      ["😋", "yum"],
      ["😛", "tongue out"],
      ["😜", "winking tongue"],
      ["🤪", "zany face"],
      ["🤗", "hugging face"],
      ["🤔", "thinking face"],
      ["🤫", "shushing face"],
      ["😐", "neutral face"],
      ["😑", "expressionless face"],
      ["🙄", "eye roll"],
      ["😏", "smirking face"],
      ["😴", "sleeping face"],
      ["😪", "sleepy face"],
      ["😷", "face with mask"],
      ["🤒", "thermometer face"],
      ["🤯", "mind blown"],
      ["🥳", "partying face"],
      ["😎", "cool face"],
      ["🤓", "nerd face"],
      ["😕", "confused face"],
      ["😟", "worried face"],
      ["😮", "open mouth"],
      ["😲", "astonished face"],
      ["🥺", "pleading face"],
      ["😢", "crying face"],
      ["😭", "loudly crying"],
      ["😱", "screaming in fear"],
      ["😤", "huffing face"],
      ["😡", "pouting face"],
      ["🤬", "cursing face"],
      ["💀", "skull"],
      ["👻", "ghost"],
      ["🤖", "robot"],
      ["💩", "pile of poo"],
      ["❤️", "red heart"],
      ["🧡", "orange heart"],
      ["💛", "yellow heart"],
      ["💚", "green heart"],
      ["💙", "blue heart"],
      ["💜", "purple heart"],
      ["🖤", "black heart"],
      ["💔", "broken heart"],
      ["💯", "hundred points"],
      ["💤", "zzz"],
    ],
  },
  {
    label: "People & Body",
    icon: "👍",
    emoji: [
      ["👍", "thumbs up"],
      ["👎", "thumbs down"],
      ["👏", "clapping hands"],
      ["🙌", "raising hands"],
      ["🙏", "folded hands"],
      ["🤝", "handshake"],
      ["👌", "ok hand"],
      ["✌️", "victory hand"],
      ["🤞", "crossed fingers"],
      ["🤟", "love-you gesture"],
      ["🤘", "sign of the horns"],
      ["👋", "waving hand"],
      ["💪", "flexed biceps"],
      ["✍️", "writing hand"],
      ["👀", "eyes"],
      ["🧠", "brain"],
      ["🫶", "heart hands"],
      ["🤷", "shrug"],
      ["🙋", "raising hand"],
      ["🙇", "bowing"],
      ["🏃", "person running"],
      ["🚶", "walking"],
      ["💃", "dancing"],
      ["🧘", "yoga"],
    ],
  },
  {
    label: "Animals & Nature",
    icon: "🐶",
    emoji: [
      ["🐶", "dog"],
      ["🐱", "cat"],
      ["🐭", "mouse"],
      ["🐰", "rabbit"],
      ["🦊", "fox"],
      ["🐻", "bear"],
      ["🐼", "panda"],
      ["🐨", "koala"],
      ["🐯", "tiger"],
      ["🦁", "lion"],
      ["🐮", "cow"],
      ["🐷", "pig"],
      ["🐸", "frog"],
      ["🐵", "monkey"],
      ["🐔", "chicken"],
      ["🐧", "penguin"],
      ["🐦", "bird"],
      ["🦋", "butterfly"],
      ["🐢", "turtle"],
      ["🐙", "octopus"],
      ["🐳", "whale"],
      ["🌸", "cherry blossom"],
      ["🌹", "rose"],
      ["🌻", "sunflower"],
      ["🌳", "tree"],
      ["🍀", "four leaf clover"],
      ["🌈", "rainbow"],
      ["☀️", "sun"],
      ["🌙", "moon"],
      ["⭐", "star"],
      ["⚡", "lightning"],
      ["❄️", "snowflake"],
      ["🔥", "fire"],
      ["💧", "droplet"],
    ],
  },
  {
    label: "Food & Drink",
    icon: "🍔",
    emoji: [
      ["🍎", "apple"],
      ["🍌", "banana"],
      ["🍇", "grapes"],
      ["🍓", "strawberry"],
      ["🍉", "watermelon"],
      ["🍑", "peach"],
      ["🥑", "avocado"],
      ["🥦", "broccoli"],
      ["🍞", "bread"],
      ["🧀", "cheese"],
      ["🍔", "hamburger"],
      ["🍟", "french fries"],
      ["🍕", "pizza"],
      ["🌮", "taco"],
      ["🍜", "noodles"],
      ["🍣", "sushi"],
      ["🥟", "dumpling"],
      ["🍚", "rice"],
      ["🍰", "cake"],
      ["🎂", "birthday cake"],
      ["🍩", "doughnut"],
      ["🍪", "cookie"],
      ["🍫", "chocolate"],
      ["🍦", "ice cream"],
      ["☕", "coffee"],
      ["🍵", "tea"],
      ["🧋", "bubble tea"],
      ["🍺", "beer"],
      ["🍷", "wine"],
      ["🥂", "cheers"],
    ],
  },
  {
    label: "Activities",
    icon: "⚽",
    emoji: [
      ["⚽", "soccer"],
      ["🏀", "basketball"],
      ["🏈", "american football"],
      ["⚾", "baseball"],
      ["🎾", "tennis"],
      ["🏐", "volleyball"],
      ["🏓", "ping pong"],
      ["🏸", "badminton"],
      ["🏊", "swimming"],
      ["🚴", "cycling"],
      ["🏋️", "weight lifting"],
      ["⛷️", "skiing"],
      ["🏆", "trophy"],
      ["🥇", "gold medal"],
      ["🎯", "bullseye"],
      ["🎮", "video game"],
      ["🎲", "dice"],
      ["🧩", "puzzle piece"],
      ["🎨", "art"],
      ["🎬", "clapper board"],
      ["🎤", "microphone"],
      ["🎧", "headphones"],
      ["🎸", "guitar"],
      ["🎹", "piano"],
      ["🎉", "party popper"],
      ["🎊", "confetti ball"],
      ["🎁", "gift"],
      ["🎈", "balloon"],
    ],
  },
  {
    label: "Travel & Places",
    icon: "✈️",
    emoji: [
      ["✈️", "airplane"],
      ["🚀", "rocket"],
      ["🚗", "car"],
      ["🚕", "taxi"],
      ["🚌", "bus"],
      ["🚇", "metro"],
      ["🚄", "high-speed train"],
      ["🚲", "bicycle"],
      ["⛵", "sailboat"],
      ["🏠", "house"],
      ["🏢", "office building"],
      ["🏥", "hospital"],
      ["🏫", "school"],
      ["⛰️", "mountain"],
      ["🏖️", "beach"],
      ["🏕️", "camping"],
      ["🗺️", "world map"],
      ["🧭", "compass"],
      ["🌍", "globe"],
      ["🌃", "night city"],
      ["🎡", "ferris wheel"],
      ["⛺", "tent"],
    ],
  },
  {
    label: "Objects",
    icon: "💡",
    emoji: [
      ["💡", "light bulb"],
      ["📱", "mobile phone"],
      ["💻", "laptop"],
      ["⌚", "watch"],
      ["📷", "camera"],
      ["📚", "books"],
      ["📝", "memo"],
      ["📌", "pushpin"],
      ["📎", "paperclip"],
      ["✏️", "pencil"],
      ["📅", "calendar"],
      ["⏰", "alarm clock"],
      ["💰", "money bag"],
      ["💳", "credit card"],
      ["🔑", "door key"],
      ["🔒", "lock"],
      ["🛒", "shopping cart"],
      ["💊", "pill"],
      ["🔔", "bell"],
      ["📦", "parcel"],
      ["✉️", "envelope"],
      ["🧸", "teddy bear"],
    ],
  },
  {
    label: "Symbols",
    icon: "❤️",
    emoji: [
      ["✅", "check mark"],
      ["❌", "cross mark"],
      ["❓", "question mark"],
      ["❗", "exclamation mark"],
      ["⚠️", "warning"],
      ["🚫", "prohibited"],
      ["➕", "plus"],
      ["➖", "minus"],
      ["🆗", "ok button"],
      ["🆕", "new button"],
      ["🔴", "red circle"],
      ["🟢", "green circle"],
      ["⬆️", "up arrow"],
      ["⬇️", "down arrow"],
      ["🔄", "repeat"],
      ["✨", "sparkles"],
      ["💥", "collision"],
      ["💬", "speech balloon"],
      ["💭", "thought balloon"],
      ["♻️", "recycling"],
      ["☮️", "peace"],
      ["🎵", "music note"],
    ],
  },
];
