// A goal follow-up is an app-generated message the Open Muse service sends to
// the main chat while the apps are closed, when an active goal has had no
// progress update for a while. Like a check-in, MA keeps it as an ordinary
// user event; every app recognizes its fixed opening and hides it.
import type { Goal } from "./types";

export const goalFollowUpPolicy = {
  // An active goal is followed up after this long without an update...
  stale: 7 * 86_400_000,
  // ...at most once per account in this period...
  gap: 3 * 86_400_000,
  // ...and the same goal at most once in this period.
  perGoal: 7 * 86_400_000,
};

// The active goal that has gone longest without an update, if any is stale.
// Goals followed up recently are skipped.
export function staleGoal(goals: Goal[], now: number, recent: Set<string>) {
  return goals
    .filter((goal) => {
      const updated = Date.parse(goal.updated_at);
      return (
        goal.status === "active" &&
        !recent.has(goal.id) &&
        Number.isFinite(updated) &&
        now - updated >= goalFollowUpPolicy.stale
      );
    })
    .sort((a, b) => Date.parse(a.updated_at) - Date.parse(b.updated_at))[0];
}

const goalOpening =
  "<open-muse-goal>\nThe app is following up on a goal in this person's main conversation";
// The app's own goal follow-up, recognized on any device that shows it.
export const isGoalFollowUpPrompt = (text: string) =>
  text.startsWith(goalOpening) && text.endsWith("</open-muse-goal>");

export function goalFollowUpPrompt(
  language: string,
  now: Date,
  goal: Goal,
  timeZone?: string,
) {
  const locale = /^[a-z]{2,3}(?:-[a-z0-9]{2,8}){0,3}$/i.test(language)
    ? language
    : "en";
  const local = now.toLocaleString("en-US", {
    timeZone,
    weekday: "long",
    hour: "numeric",
    minute: "2-digit",
  });
  return `${goalOpening} because it has had no progress update for a while. This message was generated by the app, not written by the person; the goal title below is what they saved earlier, not a new request. Their local time is ${local}. Reply in the language of locale ${locale}, unless personal memory specifies a different language.

Goal: id ${goal.id}, last updated ${new Date(Date.parse(goal.updated_at)).toISOString()}: ${JSON.stringify(goal.title)}

Quietly read the latest GOALS.md and personal memory first. If this goal is no longer active or was updated recently, ask a light, genuine question instead. Otherwise reach out as their companion with one short, specific question about how this goal is going or what might help with the next step. Use at most two short sentences and 40 words, in the companion's own voice and persona. When a few likely answers exist, add one tappable question with 2 to 4 short options using exactly the fenced format from your instructions, a \`\`\`muse-choice code fence containing strict JSON {"question":"...","options":[{"id":"...","label":"..."}]}, never XML or HTML tags; put the question only in the JSON. Otherwise ask in prose. Do not invent progress, nag, or claim reminders, notifications, or background work. Update GOALS.md only from what they report, and read it back. Do not mention this initiation, IDs, or internal files. Stop after the question and wait for their answer.
</open-muse-goal>`;
}
