import { useState } from "react";
import { ArrowUpRight, MessageCircle } from "lucide-react";
import { t } from "../shared/i18n";
import { onAndroid } from "./platform";
import { RowChevron } from "./SettingsHome";
import { Sheet } from "./MusePages";
import { ReportSheet } from "./ReportSheet";
import { shakeToReport, setShakeToReport } from "./shake";
import "./report-sheet.css";

// Settings > Help & support: ask the assistant how something works, report a
// problem, and whether shaking the iPhone opens the report form.
export function HelpSheet({
  onClose,
  onDraft,
  shakeSupported,
}: {
  onClose: () => void;
  // Puts text in the main chat composer for the person to review and send.
  onDraft: (text: string) => void;
  shakeSupported: boolean;
}) {
  const [report, setReport] = useState(false);
  const [shake, setShake] = useState(shakeToReport);
  return (
    <Sheet title={t("Help and support")} onClose={onClose} grouped>
      <ul className="settings-list">
        <li>
          <button
            className="settings-list-row help-row"
            onClick={() =>
              onDraft(
                t(
                  "How do I use Open Muse? Tell me briefly what you can do for me and how to get started.",
                ),
              )
            }
          >
            <span>{t("Ask your assistant")}</span>
            <MessageCircle size={18} aria-hidden="true" />
          </button>
        </li>
        <li>
          <button
            className="settings-list-row help-row"
            onClick={() => setReport(true)}
          >
            <span>{t("Send feedback")}</span>
            <RowChevron />
          </button>
        </li>
      </ul>
      <p className="settings-footnote">
        {t(
          "Your assistant can explain any part of the app. Feedback goes wherever you choose in the share sheet.",
        )}
      </p>
      {shakeSupported && (
        <div className="settings-switch-section">
          <label className="settings-switch-row">
            <span>
              {onAndroid()
                ? t("Shake your phone to report a problem")
                : t("Shake iPhone to report a problem")}
            </span>
            <input
              type="checkbox"
              role="switch"
              className="ios-switch"
              checked={shake}
              onChange={(event) => {
                setShakeToReport(event.target.checked);
                setShake(event.target.checked);
              }}
            />
          </label>
        </div>
      )}
      {report && <ReportSheet onClose={() => setReport(false)} />}
    </Sheet>
  );
}

const links = [
  {
    name: "Volcano Engine Privacy Policy",
    url: "https://www.volcengine.com/docs/6256/64902",
  },
  {
    name: "Volcano Engine Terms of Service",
    url: "https://www.volcengine.com/docs/6256?lang=zh",
  },
] as const;

// Settings > Legal: a note on AI replies, then the policies of Volcano
// Engine, whose Ark service runs the assistant with the person's own key.
export function LegalSheet({ onClose }: { onClose: () => void }) {
  return (
    <Sheet title={t("Legal")} onClose={onClose} grouped>
      <ul className="settings-list">
        <li>
          <div className="settings-list-row legal-note">
            <MessageCircle size={22} aria-hidden="true" />
            <span className="settings-row-text">
              {t("About AI messages")}
              <small>
                {t(
                  "Replies are generated by AI and may be inaccurate or inappropriate. Check important information before relying on it.",
                )}
              </small>
            </span>
          </div>
        </li>
      </ul>
      <h3 className="help-heading">{t("Volcano Engine")}</h3>
      <ul className="settings-list">
        {links.map((link) => (
          <li key={link.url}>
            <a
              className="settings-list-row help-row"
              href={link.url}
              target="_blank"
              rel="noopener noreferrer"
            >
              <span>{t(link.name)}</span>
              <ArrowUpRight size={18} aria-hidden="true" />
            </a>
          </li>
        ))}
      </ul>
      <p className="settings-footnote">
        {t(
          "Open Muse calls Volcano Ark with your own API key. What you send to your assistant is processed under these policies and kept in your Ark account.",
        )}
      </p>
    </Sheet>
  );
}
